feat: include author in query for User's PRs query points command
TeamNovaSoft/discord-bot pull request #54
Opened 2024-12-09 21:06 UTC by joset98

### Description

This PR addresses an issue with the query points command that returns the queries for checking user points for the year, month, etc. The command initially provided three types of queries: one for Add Point, another for Add Boosted Points, and another for Task Completed. However, it missed the query Author: @user which is essential for retrieving the PRs opened by the user. This feat ensures that the command now includes this crucial query, improving its functionality and user experience.

Fixes:
 - #46 

#### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] Doesn't break the current code.
- [x] Passes linters and test, also is building.
- [x] Doesn't have spelling or grammatical problems.
- [x] Doesn't have unnecessary comments or debugging code.
- [x] The branch is updated with the last dev branch changes.

### How to Test It:
- Run the query points Command.
- Verify that the command returns four queries: Add Point, Add Boosted Points, Task Completed, and Author: @user.
- Validate that the results are accurate and match the user's open PRs.

### Screenshots

>![image](https://github.com/user-attachments/assets/d47e2ffb-7ae1-47ed-bd19-bcd99a6ef9a2)

2024-12-10 11:34 UTC, heliomar-pena commented on src/commands/utility/search-my-points.js
> +    const openedPRs = `before: ${endDateStr} after: ${startDateStr} ${channelQueryParts} Author: @${escapedUserId}`;
I think this '@' is not needed
```suggestion
    const openedPRs = `before: ${endDateStr} after: ${startDateStr} ${channelQueryParts} Author: ${escapedUserId}`;
```
![image](https://github.com/user-attachments/assets/65218e4e-4d8d-42ba-88fb-03e0199e0d8c)

2024-12-10 11:35 UTC, heliomar-pena commented on src/commands/utility/search-my-points.js
> +    const openedPRs = `before: ${endDateStr} after: ${startDateStr} ${channelQueryParts} Author: @${escapedUserId}`;
with '@'
![image](https://github.com/user-attachments/assets/eb543fa6-45d2-49ee-9e10-9d4b0463af31)

without '@'
![image](https://github.com/user-attachments/assets/2abc57dc-b682-434a-a4c3-34aae9a0b23d)

2024-12-10 11:36 UTC, heliomar-pena requested changes
just one comment. Good work!

2024-12-10 11:52 UTC, Israel-Laguan commented on src/commands/utility/search-my-points.js
> +        \n\n**Boosted Points obtained:**\n\`\`\`${boostedPointQuery}\`\`\``,
OPTIONAL: Please remove one extra `\n` at each line

2024-12-12 15:14 UTC, Israel-Laguan approved these changes

2024-12-12 20:09 UTC, heliomar-pena approved these changes
LGTM!

2024-12-12 20:09 UTC, merged